// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competitors.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCompetitorForUser = `-- name: CreateCompetitorForUser :one
INSERT INTO competitors (
    id,
    project_id,
    name,
    domain
)
SELECT
    $1,
    $2,
    $3,
    $4
FROM projects p
WHERE p.id = $2
  AND p.user_id = $5
RETURNING id, project_id, name, domain, created_at, updated_at
`

type CreateCompetitorForUserParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
	Domain    *string   `json:"domain"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateCompetitorForUser(ctx context.Context, arg CreateCompetitorForUserParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, createCompetitorForUser,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Domain,
		arg.UserID,
	)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompetitorForUser = `-- name: DeleteCompetitorForUser :execrows
DELETE FROM competitors c
USING projects p
WHERE c.id = $1
  AND c.project_id = p.id
  AND p.user_id = $2
`

type DeleteCompetitorForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCompetitorForUser(ctx context.Context, arg DeleteCompetitorForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitorForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCompetitorsByProject = `-- name: ListCompetitorsByProject :many
SELECT c.id, c.project_id, c.name, c.domain, c.created_at, c.updated_at
FROM competitors c
WHERE c.project_id = $1
ORDER BY c.created_at DESC
`

type ListCompetitorsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ListCompetitorsByProject(ctx context.Context, arg ListCompetitorsByProjectParams) ([]Competitor, error) {
	rows, err := q.db.Query(ctx, listCompetitorsByProject, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competitor
	for rows.Next() {
		var i Competitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitorsByProjectForUser = `-- name: ListCompetitorsByProjectForUser :many
SELECT c.id, c.project_id, c.name, c.domain, c.created_at, c.updated_at
FROM competitors c
JOIN projects p
  ON p.id = c.project_id
WHERE c.project_id = $1
  AND p.user_id = $2
ORDER BY c.created_at DESC
`

type ListCompetitorsByProjectForUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListCompetitorsByProjectForUser(ctx context.Context, arg ListCompetitorsByProjectForUserParams) ([]Competitor, error) {
	rows, err := q.db.Query(ctx, listCompetitorsByProjectForUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competitor
	for rows.Next() {
		var i Competitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
