// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_runs.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimScanRun = `-- name: ClaimScanRun :one
UPDATE scan_runs
SET
    status = 'running',
    started_at = now()
WHERE id = $1
  AND scan_id = $2
  AND (
      status = 'pending'
      OR (status = 'running' AND started_at <= now() - interval '15 minutes')
  )
RETURNING id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
`

type ClaimScanRunParams struct {
	ID     uuid.UUID `json:"id"`
	ScanID uuid.UUID `json:"scan_id"`
}

func (q *Queries) ClaimScanRun(ctx context.Context, arg ClaimScanRunParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, claimScanRun, arg.ID, arg.ScanID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const claimScansForWorkers = `-- name: ClaimScansForWorkers :many
WITH eligible_scans AS (
    SELECT s.id
    FROM scans s
    WHERE (
        s.status = 'pending'
        OR (s.status = 'running' AND s.started_at <= now() - interval '15 minutes')
    )
      AND EXISTS (
          SELECT 1
          FROM scan_runs sr
          WHERE sr.scan_id = s.id
            AND (
                sr.status = 'pending'
                OR (sr.status = 'running' AND sr.started_at <= now() - interval '15 minutes')
            )
      )
    ORDER BY s.created_at ASC
    FOR UPDATE OF s SKIP LOCKED
)
UPDATE scans s
SET status = 'running',
    started_at = now()
FROM eligible_scans es
WHERE s.id = es.id
RETURNING s.id
`

func (q *Queries) ClaimScansForWorkers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimScansForWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScanRuns = `-- name: CreateScanRuns :execrows
INSERT INTO scan_runs (
    id,
    scan_id,
    engine_id,
    prompt_id,
    provider_key_id
)
SELECT
    unnest($1::uuid[]),
    $2,
    unnest($3::text[]),
    unnest($4::uuid[]),
    unnest($5::uuid[])
`

type CreateScanRunsParams struct {
	Ids            []uuid.UUID `json:"ids"`
	ScanID         uuid.UUID   `json:"scan_id"`
	EngineIds      []string    `json:"engine_ids"`
	PromptIds      []uuid.UUID `json:"prompt_ids"`
	ProviderKeyIds []uuid.UUID `json:"provider_key_ids"`
}

func (q *Queries) CreateScanRuns(ctx context.Context, arg CreateScanRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createScanRuns,
		arg.Ids,
		arg.ScanID,
		arg.EngineIds,
		arg.PromptIds,
		arg.ProviderKeyIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEligibleScanRunsForWorkers = `-- name: GetEligibleScanRunsForWorkers :many
SELECT
    p.brand_name AS brand_name,
    p.domain AS brand_domain,
    s.id AS scan_id,
    sr.id AS scan_run_id,
    sr.engine_id,
    sr.prompt_id,
    sr.provider_key_id,
    sr.try_number,
    sr.status AS scan_run_status,
    s.status AS scan_status,
    p.language,
    p.region,
    pr.text AS prompt_text,
    pr.active AS prompt_active,
    pk.encrypted_key,
    pk.key_nonce,
    pk.active AS provider_key_active,
    pk.monthly_run_limit,
    pk.monthly_runs_used
FROM scan_runs sr
JOIN scans s
    ON s.id = sr.scan_id
JOIN projects p
    ON p.id = s.project_id
JOIN prompts pr
    ON pr.id = sr.prompt_id
JOIN provider_keys pk
    ON pk.id = sr.provider_key_id
WHERE sr.scan_id = ANY($1::uuid[])
  AND (
      sr.status = 'pending'
      OR (sr.status = 'running' AND sr.started_at <= now() - interval '15 minutes')
  )
ORDER BY sr.created_at ASC
`

type GetEligibleScanRunsForWorkersParams struct {
	ScanIds []uuid.UUID `json:"scan_ids"`
}

type GetEligibleScanRunsForWorkersRow struct {
	BrandName         string    `json:"brand_name"`
	BrandDomain       string    `json:"brand_domain"`
	ScanID            uuid.UUID `json:"scan_id"`
	ScanRunID         uuid.UUID `json:"scan_run_id"`
	EngineID          string    `json:"engine_id"`
	PromptID          uuid.UUID `json:"prompt_id"`
	ProviderKeyID     uuid.UUID `json:"provider_key_id"`
	TryNumber         int32     `json:"try_number"`
	ScanRunStatus     string    `json:"scan_run_status"`
	ScanStatus        string    `json:"scan_status"`
	Language          string    `json:"language"`
	Region            string    `json:"region"`
	PromptText        string    `json:"prompt_text"`
	PromptActive      bool      `json:"prompt_active"`
	EncryptedKey      []byte    `json:"encrypted_key"`
	KeyNonce          []byte    `json:"key_nonce"`
	ProviderKeyActive bool      `json:"provider_key_active"`
	MonthlyRunLimit   *int32    `json:"monthly_run_limit"`
	MonthlyRunsUsed   int32     `json:"monthly_runs_used"`
}

func (q *Queries) GetEligibleScanRunsForWorkers(ctx context.Context, arg GetEligibleScanRunsForWorkersParams) ([]GetEligibleScanRunsForWorkersRow, error) {
	rows, err := q.db.Query(ctx, getEligibleScanRunsForWorkers, arg.ScanIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEligibleScanRunsForWorkersRow
	for rows.Next() {
		var i GetEligibleScanRunsForWorkersRow
		if err := rows.Scan(
			&i.BrandName,
			&i.BrandDomain,
			&i.ScanID,
			&i.ScanRunID,
			&i.EngineID,
			&i.PromptID,
			&i.ProviderKeyID,
			&i.TryNumber,
			&i.ScanRunStatus,
			&i.ScanStatus,
			&i.Language,
			&i.Region,
			&i.PromptText,
			&i.PromptActive,
			&i.EncryptedKey,
			&i.KeyNonce,
			&i.ProviderKeyActive,
			&i.MonthlyRunLimit,
			&i.MonthlyRunsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanRunByID = `-- name: GetScanRunByID :one
SELECT id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
FROM scan_runs
WHERE id = $1
`

type GetScanRunByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetScanRunByID(ctx context.Context, arg GetScanRunByIDParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, getScanRunByID, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateScanRun = `-- name: UpdateScanRun :one
UPDATE scan_runs
SET
    scan_id = $1,
    engine_id = $2,
    prompt_id = $3,
    provider_key_id = $4,
    try_number = $5,
    status = $6,
    answer_text = $7,
    raw_response = $8,
    brand_mentioned = $9,
    brand_domain_cited = $10,
    competitors_mentioned = $11,
    cited_domains = $12,
    error = $13,
    -- COALESCE so a caller that omits these does not blank out timestamps
    -- already set by UpdateScanRunStateByID.
    started_at = COALESCE($14, started_at),
    finished_at = COALESCE($15, finished_at)
WHERE id = $16
RETURNING id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
`

type UpdateScanRunParams struct {
	ScanID               uuid.UUID          `json:"scan_id"`
	EngineID             string             `json:"engine_id"`
	PromptID             uuid.UUID          `json:"prompt_id"`
	ProviderKeyID        uuid.UUID          `json:"provider_key_id"`
	TryNumber            int32              `json:"try_number"`
	Status               string             `json:"status"`
	AnswerText           *string            `json:"answer_text"`
	RawResponse          []byte             `json:"raw_response"`
	BrandMentioned       *bool              `json:"brand_mentioned"`
	BrandDomainCited     *bool              `json:"brand_domain_cited"`
	CompetitorsMentioned []byte             `json:"competitors_mentioned"`
	CitedDomains         []byte             `json:"cited_domains"`
	Error                *string            `json:"error"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	ID                   uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateScanRun(ctx context.Context, arg UpdateScanRunParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, updateScanRun,
		arg.ScanID,
		arg.EngineID,
		arg.PromptID,
		arg.ProviderKeyID,
		arg.TryNumber,
		arg.Status,
		arg.AnswerText,
		arg.RawResponse,
		arg.BrandMentioned,
		arg.BrandDomainCited,
		arg.CompetitorsMentioned,
		arg.CitedDomains,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateScanRunAnalysis = `-- name: UpdateScanRunAnalysis :exec
UPDATE scan_runs
SET
    brand_mentioned = $1,
    brand_domain_cited = $2,
    competitors_mentioned = $3,
    cited_domains = $4
WHERE id = $5
  AND scan_id = $6
`

type UpdateScanRunAnalysisParams struct {
	BrandMentioned       *bool     `json:"brand_mentioned"`
	BrandDomainCited     *bool     `json:"brand_domain_cited"`
	CompetitorsMentioned []byte    `json:"competitors_mentioned"`
	CitedDomains         []byte    `json:"cited_domains"`
	ID                   uuid.UUID `json:"id"`
	ScanID               uuid.UUID `json:"scan_id"`
}

func (q *Queries) UpdateScanRunAnalysis(ctx context.Context, arg UpdateScanRunAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateScanRunAnalysis,
		arg.BrandMentioned,
		arg.BrandDomainCited,
		arg.CompetitorsMentioned,
		arg.CitedDomains,
		arg.ID,
		arg.ScanID,
	)
	return err
}

const updateScanRunStateByID = `-- name: UpdateScanRunStateByID :one
UPDATE scan_runs
SET
    status = $1,
    error = $2,
    started_at = CASE
        WHEN $1 = 'running' THEN now()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1 IN ('completed', 'failed', 'canceled') THEN now()
        ELSE finished_at
    END
WHERE id = $3
RETURNING id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
`

type UpdateScanRunStateByIDParams struct {
	Status string    `json:"status"`
	Error  *string   `json:"error"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateScanRunStateByID(ctx context.Context, arg UpdateScanRunStateByIDParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, updateScanRunStateByID, arg.Status, arg.Error, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
