// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Competitor struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Domain    *string            `json:"domain"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	BrandName string             `json:"brand_name"`
	Domain    string             `json:"domain"`
	Language  string             `json:"language"`
	Region    string             `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectEngine struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	EngineID      string             `json:"engine_id"`
	ProviderKeyID uuid.UUID          `json:"provider_key_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Prompt struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Text      string             `json:"text"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProviderKey struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	EngineID        string             `json:"engine_id"`
	Name            string             `json:"name"`
	EncryptedKey    []byte             `json:"encrypted_key"`
	KeyNonce        []byte             `json:"key_nonce"`
	Active          bool               `json:"active"`
	MonthlyRunLimit *int32             `json:"monthly_run_limit"`
	MonthlyRunsUsed int32              `json:"monthly_runs_used"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Scan struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Status         string             `json:"status"`
	TriesPerPrompt int32              `json:"tries_per_prompt"`
	TotalRuns      int32              `json:"total_runs"`
	CompletedRuns  int32              `json:"completed_runs"`
	FailedRuns     int32              `json:"failed_runs"`
	Summary        []byte             `json:"summary"`
	Error          *string            `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type ScanRun struct {
	ID                   uuid.UUID          `json:"id"`
	ScanID               uuid.UUID          `json:"scan_id"`
	EngineID             string             `json:"engine_id"`
	PromptID             uuid.UUID          `json:"prompt_id"`
	ProviderKeyID        uuid.UUID          `json:"provider_key_id"`
	TryNumber            int32              `json:"try_number"`
	Status               string             `json:"status"`
	AnswerText           *string            `json:"answer_text"`
	RawResponse          []byte             `json:"raw_response"`
	BrandMentioned       *bool              `json:"brand_mentioned"`
	BrandDomainCited     *bool              `json:"brand_domain_cited"`
	CompetitorsMentioned []byte             `json:"competitors_mentioned"`
	CitedDomains         []byte             `json:"cited_domains"`
	Error                *string            `json:"error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Password  *string            `json:"password"`
	Name      *string            `json:"name"`
	TierName  string             `json:"tier_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
