// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    user_id,
    brand_name,
    domain,
    language,
    region
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, brand_name, domain, language, region, created_at, updated_at
`

type CreateProjectParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	BrandName string    `json:"brand_name"`
	Domain    string    `json:"domain"`
	Language  string    `json:"language"`
	Region    string    `json:"region"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.BrandName,
		arg.Domain,
		arg.Language,
		arg.Region,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandName,
		&i.Domain,
		&i.Language,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, brand_name, domain, language, region, created_at, updated_at
FROM projects
WHERE id = $1
`

type GetProjectByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandName,
		&i.Domain,
		&i.Language,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIDForUser = `-- name: GetProjectByIDForUser :one
SELECT id, user_id, brand_name, domain, language, region, created_at, updated_at
FROM projects
WHERE id = $1
  AND user_id = $2
`

type GetProjectByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandName,
		&i.Domain,
		&i.Language,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, user_id, brand_name, domain, language, region, created_at, updated_at
FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListProjectsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListProjectsByUserID(ctx context.Context, arg ListProjectsByUserIDParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandName,
			&i.Domain,
			&i.Language,
			&i.Region,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    brand_name = $2,
    domain = $3,
    language = $4,
    region = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, brand_name, domain, language, region, created_at, updated_at
`

type UpdateProjectParams struct {
	ID        uuid.UUID `json:"id"`
	BrandName string    `json:"brand_name"`
	Domain    string    `json:"domain"`
	Language  string    `json:"language"`
	Region    string    `json:"region"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.BrandName,
		arg.Domain,
		arg.Language,
		arg.Region,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandName,
		&i.Domain,
		&i.Language,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectForUser = `-- name: UpdateProjectForUser :one
UPDATE projects
SET
    brand_name = $3,
    domain = $4,
    language = $5,
    region = $6,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, brand_name, domain, language, region, created_at, updated_at
`

type UpdateProjectForUserParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	BrandName string    `json:"brand_name"`
	Domain    string    `json:"domain"`
	Language  string    `json:"language"`
	Region    string    `json:"region"`
}

func (q *Queries) UpdateProjectForUser(ctx context.Context, arg UpdateProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectForUser,
		arg.ID,
		arg.UserID,
		arg.BrandName,
		arg.Domain,
		arg.Language,
		arg.Region,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandName,
		&i.Domain,
		&i.Language,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
