// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_engine.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProjectEngineForUser = `-- name: CreateProjectEngineForUser :one
INSERT INTO project_engines (
    project_id,
    engine_id,
    provider_key_id
)
SELECT
    $1,
    $2,
    $3
FROM projects p
JOIN provider_keys pk
    ON pk.id = $3
WHERE p.id = $1
  AND p.user_id = $4
  AND pk.user_id = $4
  AND pk.engine_id = $2
RETURNING project_id, engine_id, provider_key_id, created_at, updated_at
`

type CreateProjectEngineForUserParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	EngineID      string    `json:"engine_id"`
	ProviderKeyID uuid.UUID `json:"provider_key_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateProjectEngineForUser(ctx context.Context, arg CreateProjectEngineForUserParams) (ProjectEngine, error) {
	row := q.db.QueryRow(ctx, createProjectEngineForUser,
		arg.ProjectID,
		arg.EngineID,
		arg.ProviderKeyID,
		arg.UserID,
	)
	var i ProjectEngine
	err := row.Scan(
		&i.ProjectID,
		&i.EngineID,
		&i.ProviderKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectEngineForUser = `-- name: DeleteProjectEngineForUser :exec
DELETE FROM project_engines pe
USING projects p
WHERE pe.project_id = $1
  AND pe.engine_id = $2
  AND p.id = pe.project_id
  AND p.user_id = $3
`

type DeleteProjectEngineForUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	EngineID  string    `json:"engine_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectEngineForUser(ctx context.Context, arg DeleteProjectEngineForUserParams) error {
	_, err := q.db.Exec(ctx, deleteProjectEngineForUser, arg.ProjectID, arg.EngineID, arg.UserID)
	return err
}

const updateProjectEngineForUser = `-- name: UpdateProjectEngineForUser :one
UPDATE project_engines pe
SET
    provider_key_id = $1,
    updated_at = now()
FROM projects p
JOIN provider_keys pk
    ON pk.id = $1
WHERE pe.project_id = $2
  AND pe.engine_id = $3
  AND p.id = pe.project_id
  AND p.user_id = $4
  AND pk.user_id = $4
  AND pk.engine_id = pe.engine_id
RETURNING pe.project_id, pe.engine_id, pe.provider_key_id, pe.created_at, pe.updated_at
`

type UpdateProjectEngineForUserParams struct {
	ProviderKeyID uuid.UUID `json:"provider_key_id"`
	ProjectID     uuid.UUID `json:"project_id"`
	EngineID      string    `json:"engine_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateProjectEngineForUser(ctx context.Context, arg UpdateProjectEngineForUserParams) (ProjectEngine, error) {
	row := q.db.QueryRow(ctx, updateProjectEngineForUser,
		arg.ProviderKeyID,
		arg.ProjectID,
		arg.EngineID,
		arg.UserID,
	)
	var i ProjectEngine
	err := row.Scan(
		&i.ProjectID,
		&i.EngineID,
		&i.ProviderKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
