// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createPromptForUser = `-- name: CreatePromptForUser :one
INSERT INTO prompts (
    id,
    project_id,
    text,
    active
)
SELECT
    $1,
    $2,
    $3,
    $4
FROM projects p
WHERE p.id = $2
  AND p.user_id = $5
RETURNING id, project_id, text, active, created_at, updated_at
`

type CreatePromptForUserParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Active    bool      `json:"active"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePromptForUser(ctx context.Context, arg CreatePromptForUserParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPromptForUser,
		arg.ID,
		arg.ProjectID,
		arg.Text,
		arg.Active,
		arg.UserID,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromptsForUser = `-- name: CreatePromptsForUser :execrows
INSERT INTO prompts (
    id,
    project_id,
    text,
    active
)
SELECT
    unnest($1::uuid[]),
    $2,
    unnest($3::text[]),
    unnest($4::boolean[])
WHERE EXISTS (
    SELECT 1
    FROM projects p
    WHERE p.id = $2
      AND p.user_id = $5
)
`

type CreatePromptsForUserParams struct {
	Ids       []uuid.UUID `json:"ids"`
	ProjectID uuid.UUID   `json:"project_id"`
	Texts     []string    `json:"texts"`
	Actives   []bool      `json:"actives"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) CreatePromptsForUser(ctx context.Context, arg CreatePromptsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPromptsForUser,
		arg.Ids,
		arg.ProjectID,
		arg.Texts,
		arg.Actives,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPromptByIDForUser = `-- name: GetPromptByIDForUser :one
SELECT pr.id, pr.project_id, pr.text, pr.active, pr.created_at, pr.updated_at
FROM prompts pr
JOIN projects p
  ON p.id = pr.project_id
WHERE pr.id = $1
  AND p.user_id = $2
`

type GetPromptByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPromptByIDForUser(ctx context.Context, arg GetPromptByIDForUserParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByIDForUser, arg.ID, arg.UserID)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptsByProjectForUser = `-- name: ListPromptsByProjectForUser :many
SELECT pr.id, pr.project_id, pr.text, pr.active, pr.created_at, pr.updated_at
FROM prompts pr
JOIN projects p
  ON p.id = pr.project_id
WHERE pr.project_id = $1
  AND p.user_id = $2
ORDER BY pr.created_at DESC
`

type ListPromptsByProjectForUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListPromptsByProjectForUser(ctx context.Context, arg ListPromptsByProjectForUserParams) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, listPromptsByProjectForUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptForUser = `-- name: UpdatePromptForUser :one
UPDATE prompts pr
SET
    text = $1,
    active = $2,
    updated_at = now()
FROM projects p
WHERE pr.id = $3
  AND pr.project_id = p.id
  AND p.user_id = $4
RETURNING pr.id, pr.project_id, pr.text, pr.active, pr.created_at, pr.updated_at
`

type UpdatePromptForUserParams struct {
	Text   string    `json:"text"`
	Active bool      `json:"active"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePromptForUser(ctx context.Context, arg UpdatePromptForUserParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, updatePromptForUser,
		arg.Text,
		arg.Active,
		arg.ID,
		arg.UserID,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
