// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_key.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProviderKey = `-- name: CreateProviderKey :one
INSERT INTO provider_keys (
    id,
    user_id,
    engine_id,
    name,
    encrypted_key,
    key_nonce,
    active,
    monthly_run_limit
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
`

type CreateProviderKeyParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	EngineID        string    `json:"engine_id"`
	Name            string    `json:"name"`
	EncryptedKey    []byte    `json:"encrypted_key"`
	KeyNonce        []byte    `json:"key_nonce"`
	Active          bool      `json:"active"`
	MonthlyRunLimit *int32    `json:"monthly_run_limit"`
}

func (q *Queries) CreateProviderKey(ctx context.Context, arg CreateProviderKeyParams) (ProviderKey, error) {
	row := q.db.QueryRow(ctx, createProviderKey,
		arg.ID,
		arg.UserID,
		arg.EngineID,
		arg.Name,
		arg.EncryptedKey,
		arg.KeyNonce,
		arg.Active,
		arg.MonthlyRunLimit,
	)
	var i ProviderKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EngineID,
		&i.Name,
		&i.EncryptedKey,
		&i.KeyNonce,
		&i.Active,
		&i.MonthlyRunLimit,
		&i.MonthlyRunsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderKeyByID = `-- name: GetProviderKeyByID :one
SELECT id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
FROM provider_keys
WHERE id = $1
`

type GetProviderKeyByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetProviderKeyByID(ctx context.Context, arg GetProviderKeyByIDParams) (ProviderKey, error) {
	row := q.db.QueryRow(ctx, getProviderKeyByID, arg.ID)
	var i ProviderKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EngineID,
		&i.Name,
		&i.EncryptedKey,
		&i.KeyNonce,
		&i.Active,
		&i.MonthlyRunLimit,
		&i.MonthlyRunsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderKeyByIDForUser = `-- name: GetProviderKeyByIDForUser :one
SELECT id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
FROM provider_keys
WHERE id = $1
  AND user_id = $2
`

type GetProviderKeyByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProviderKeyByIDForUser(ctx context.Context, arg GetProviderKeyByIDForUserParams) (ProviderKey, error) {
	row := q.db.QueryRow(ctx, getProviderKeyByIDForUser, arg.ID, arg.UserID)
	var i ProviderKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EngineID,
		&i.Name,
		&i.EncryptedKey,
		&i.KeyNonce,
		&i.Active,
		&i.MonthlyRunLimit,
		&i.MonthlyRunsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderKeysByUserID = `-- name: ListProviderKeysByUserID :many
SELECT id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
FROM provider_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListProviderKeysByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListProviderKeysByUserID(ctx context.Context, arg ListProviderKeysByUserIDParams) ([]ProviderKey, error) {
	rows, err := q.db.Query(ctx, listProviderKeysByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderKey
	for rows.Next() {
		var i ProviderKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EngineID,
			&i.Name,
			&i.EncryptedKey,
			&i.KeyNonce,
			&i.Active,
			&i.MonthlyRunLimit,
			&i.MonthlyRunsUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderKeysByUserIDAndEngine = `-- name: ListProviderKeysByUserIDAndEngine :many
SELECT id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
FROM provider_keys
WHERE user_id = $1
  AND engine_id = $2
ORDER BY created_at DESC
`

type ListProviderKeysByUserIDAndEngineParams struct {
	UserID   uuid.UUID `json:"user_id"`
	EngineID string    `json:"engine_id"`
}

func (q *Queries) ListProviderKeysByUserIDAndEngine(ctx context.Context, arg ListProviderKeysByUserIDAndEngineParams) ([]ProviderKey, error) {
	rows, err := q.db.Query(ctx, listProviderKeysByUserIDAndEngine, arg.UserID, arg.EngineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderKey
	for rows.Next() {
		var i ProviderKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EngineID,
			&i.Name,
			&i.EncryptedKey,
			&i.KeyNonce,
			&i.Active,
			&i.MonthlyRunLimit,
			&i.MonthlyRunsUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderKeyMetadataForUser = `-- name: UpdateProviderKeyMetadataForUser :one
UPDATE provider_keys
SET
    name = $3,
    active = $4,
    monthly_run_limit = $5,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, engine_id, name, encrypted_key, key_nonce, active, monthly_run_limit, monthly_runs_used, created_at, updated_at
`

type UpdateProviderKeyMetadataForUserParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Name            string    `json:"name"`
	Active          bool      `json:"active"`
	MonthlyRunLimit *int32    `json:"monthly_run_limit"`
}

func (q *Queries) UpdateProviderKeyMetadataForUser(ctx context.Context, arg UpdateProviderKeyMetadataForUserParams) (ProviderKey, error) {
	row := q.db.QueryRow(ctx, updateProviderKeyMetadataForUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Active,
		arg.MonthlyRunLimit,
	)
	var i ProviderKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EngineID,
		&i.Name,
		&i.EncryptedKey,
		&i.KeyNonce,
		&i.Active,
		&i.MonthlyRunLimit,
		&i.MonthlyRunsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
