// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
    id,
    project_id,
    status,
    tries_per_prompt,
    total_runs,
    completed_runs,
    failed_runs,
    summary,
    error,
    started_at,
    finished_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, project_id, status, tries_per_prompt, total_runs, completed_runs, failed_runs, summary, error, created_at, started_at, finished_at
`

type CreateScanParams struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Status         string             `json:"status"`
	TriesPerPrompt int32              `json:"tries_per_prompt"`
	TotalRuns      int32              `json:"total_runs"`
	CompletedRuns  int32              `json:"completed_runs"`
	FailedRuns     int32              `json:"failed_runs"`
	Summary        []byte             `json:"summary"`
	Error          *string            `json:"error"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.TriesPerPrompt,
		arg.TotalRuns,
		arg.CompletedRuns,
		arg.FailedRuns,
		arg.Summary,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.TriesPerPrompt,
		&i.TotalRuns,
		&i.CompletedRuns,
		&i.FailedRuns,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getScanByID = `-- name: GetScanByID :one
SELECT id, project_id, status, tries_per_prompt, total_runs, completed_runs, failed_runs, summary, error, created_at, started_at, finished_at
FROM scans
WHERE id = $1
`

type GetScanByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetScanByID(ctx context.Context, arg GetScanByIDParams) (Scan, error) {
	row := q.db.QueryRow(ctx, getScanByID, arg.ID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.TriesPerPrompt,
		&i.TotalRuns,
		&i.CompletedRuns,
		&i.FailedRuns,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementScanCompletedRuns = `-- name: IncrementScanCompletedRuns :exec
UPDATE scans
SET completed_runs = completed_runs + 1
WHERE id = $1
`

type IncrementScanCompletedRunsParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) IncrementScanCompletedRuns(ctx context.Context, arg IncrementScanCompletedRunsParams) error {
	_, err := q.db.Exec(ctx, incrementScanCompletedRuns, arg.ID)
	return err
}

const incrementScanFailedRuns = `-- name: IncrementScanFailedRuns :exec
UPDATE scans
SET failed_runs = failed_runs + 1
WHERE id = $1
`

type IncrementScanFailedRunsParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) IncrementScanFailedRuns(ctx context.Context, arg IncrementScanFailedRunsParams) error {
	_, err := q.db.Exec(ctx, incrementScanFailedRuns, arg.ID)
	return err
}

const updateScan = `-- name: UpdateScan :one
UPDATE scans
SET
    project_id = $1,
    status = $2,
    tries_per_prompt = $3,
    total_runs = $4,
    completed_runs = $5,
    failed_runs = $6,
    summary = $7,
    error = $8,
    started_at = $9,
    finished_at = $10
WHERE id = $11
RETURNING id, project_id, status, tries_per_prompt, total_runs, completed_runs, failed_runs, summary, error, created_at, started_at, finished_at
`

type UpdateScanParams struct {
	ProjectID      uuid.UUID          `json:"project_id"`
	Status         string             `json:"status"`
	TriesPerPrompt int32              `json:"tries_per_prompt"`
	TotalRuns      int32              `json:"total_runs"`
	CompletedRuns  int32              `json:"completed_runs"`
	FailedRuns     int32              `json:"failed_runs"`
	Summary        []byte             `json:"summary"`
	Error          *string            `json:"error"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateScan(ctx context.Context, arg UpdateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateScan,
		arg.ProjectID,
		arg.Status,
		arg.TriesPerPrompt,
		arg.TotalRuns,
		arg.CompletedRuns,
		arg.FailedRuns,
		arg.Summary,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.TriesPerPrompt,
		&i.TotalRuns,
		&i.CompletedRuns,
		&i.FailedRuns,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
