// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_runs.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getScanRunByID = `-- name: GetScanRunByID :one
SELECT id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
FROM scan_runs
WHERE id = $1
`

type GetScanRunByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetScanRunByID(ctx context.Context, arg GetScanRunByIDParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, getScanRunByID, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getScansForWorkers = `-- name: GetScansForWorkers :many
WITH claimed AS (
    SELECT sr.id
    FROM scan_runs sr
    WHERE sr.status = 'pending'
       OR (sr.status = 'running' AND sr.started_at <= now() - interval '30 seconds')
    ORDER BY sr.created_at ASC
    FOR UPDATE SKIP LOCKED
), updated AS (
    UPDATE scan_runs sr
    SET status = 'pending',
        updated_at = now()
    FROM claimed c
    WHERE sr.id = c.id
    RETURNING sr.id, sr.scan_id, sr.engine_id, sr.prompt_id, sr.provider_key_id, sr.try_number, sr.status, sr.answer_text, sr.raw_response, sr.brand_mentioned, sr.brand_domain_cited, sr.competitors_mentioned, sr.cited_domains, sr.error, sr.created_at, sr.started_at, sr.finished_at
)
SELECT
    p.brand_name AS brand_name,
    p.domain AS brand_domain,
    s.id AS scan_id,
    sr.id AS scan_run_id,
    sr.engine_id,
    sr.prompt_id,
    sr.provider_key_id,
    sr.try_number,
    sr.status AS scan_run_status,
    s.status AS scan_status,
    s.tries_per_prompt,
    p.language,
    p.region,
    pr.text AS prompt_text,
    pr.active AS prompt_active,
    pk.encrypted_key,
    pk.key_nonce,
    pk.active AS provider_key_active,
    pk.monthly_run_limit,
    pk.monthly_runs_used
FROM updated sr
JOIN scans s
    ON s.id = sr.scan_id
JOIN projects p
    ON p.id = s.project_id
JOIN prompts pr
    ON pr.id = sr.prompt_id
JOIN provider_keys pk
    ON pk.id = sr.provider_key_id
ORDER BY sr.created_at ASC
`

type GetScansForWorkersRow struct {
	BrandName         string    `json:"brand_name"`
	BrandDomain       string    `json:"brand_domain"`
	ScanID            uuid.UUID `json:"scan_id"`
	ScanRunID         uuid.UUID `json:"scan_run_id"`
	EngineID          string    `json:"engine_id"`
	PromptID          uuid.UUID `json:"prompt_id"`
	ProviderKeyID     uuid.UUID `json:"provider_key_id"`
	TryNumber         int32     `json:"try_number"`
	ScanRunStatus     string    `json:"scan_run_status"`
	ScanStatus        string    `json:"scan_status"`
	TriesPerPrompt    int32     `json:"tries_per_prompt"`
	Language          string    `json:"language"`
	Region            string    `json:"region"`
	PromptText        string    `json:"prompt_text"`
	PromptActive      bool      `json:"prompt_active"`
	EncryptedKey      []byte    `json:"encrypted_key"`
	KeyNonce          []byte    `json:"key_nonce"`
	ProviderKeyActive bool      `json:"provider_key_active"`
	MonthlyRunLimit   *int32    `json:"monthly_run_limit"`
	MonthlyRunsUsed   int32     `json:"monthly_runs_used"`
}

func (q *Queries) GetScansForWorkers(ctx context.Context) ([]GetScansForWorkersRow, error) {
	rows, err := q.db.Query(ctx, getScansForWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScansForWorkersRow
	for rows.Next() {
		var i GetScansForWorkersRow
		if err := rows.Scan(
			&i.BrandName,
			&i.BrandDomain,
			&i.ScanID,
			&i.ScanRunID,
			&i.EngineID,
			&i.PromptID,
			&i.ProviderKeyID,
			&i.TryNumber,
			&i.ScanRunStatus,
			&i.ScanStatus,
			&i.TriesPerPrompt,
			&i.Language,
			&i.Region,
			&i.PromptText,
			&i.PromptActive,
			&i.EncryptedKey,
			&i.KeyNonce,
			&i.ProviderKeyActive,
			&i.MonthlyRunLimit,
			&i.MonthlyRunsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanRun = `-- name: UpdateScanRun :one
UPDATE scan_runs
SET
    scan_id = $1,
    engine_id = $2,
    prompt_id = $3,
    provider_key_id = $4,
    try_number = $5,
    status = $6,
    answer_text = $7,
    raw_response = $8,
    brand_mentioned = $9,
    brand_domain_cited = $10,
    competitors_mentioned = $11,
    cited_domains = $12,
    error = $13,
    started_at = $14,
    finished_at = $15
WHERE id = $16
RETURNING id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
`

type UpdateScanRunParams struct {
	ScanID               uuid.UUID          `json:"scan_id"`
	EngineID             string             `json:"engine_id"`
	PromptID             uuid.UUID          `json:"prompt_id"`
	ProviderKeyID        uuid.UUID          `json:"provider_key_id"`
	TryNumber            int32              `json:"try_number"`
	Status               string             `json:"status"`
	AnswerText           *string            `json:"answer_text"`
	RawResponse          []byte             `json:"raw_response"`
	BrandMentioned       *bool              `json:"brand_mentioned"`
	BrandDomainCited     *bool              `json:"brand_domain_cited"`
	CompetitorsMentioned []byte             `json:"competitors_mentioned"`
	CitedDomains         []byte             `json:"cited_domains"`
	Error                *string            `json:"error"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	ID                   uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateScanRun(ctx context.Context, arg UpdateScanRunParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, updateScanRun,
		arg.ScanID,
		arg.EngineID,
		arg.PromptID,
		arg.ProviderKeyID,
		arg.TryNumber,
		arg.Status,
		arg.AnswerText,
		arg.RawResponse,
		arg.BrandMentioned,
		arg.BrandDomainCited,
		arg.CompetitorsMentioned,
		arg.CitedDomains,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateScanRunStateByID = `-- name: UpdateScanRunStateByID :one
UPDATE scan_runs
SET
    status = $1,
    started_at = CASE
        WHEN $1 = 'running' THEN now()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1 IN ('completed', 'failed', 'canceled') THEN now()
        ELSE finished_at
    END
WHERE id = $2
RETURNING id, scan_id, engine_id, prompt_id, provider_key_id, try_number, status, answer_text, raw_response, brand_mentioned, brand_domain_cited, competitors_mentioned, cited_domains, error, created_at, started_at, finished_at
`

type UpdateScanRunStateByIDParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateScanRunStateByID(ctx context.Context, arg UpdateScanRunStateByIDParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, updateScanRunStateByID, arg.Status, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.EngineID,
		&i.PromptID,
		&i.ProviderKeyID,
		&i.TryNumber,
		&i.Status,
		&i.AnswerText,
		&i.RawResponse,
		&i.BrandMentioned,
		&i.BrandDomainCited,
		&i.CompetitorsMentioned,
		&i.CitedDomains,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
